# OR

In [23]:
import numpy as np
import matplotlib.pyplot as plt

### 1. Data

In [24]:
X = [[0,0],[1,0],[0,1],[1,1]]
t = [0,1,1,1]

### 2. Model

In [25]:
def perc(x):
    f=np.dot(w,x)+b
    if f>=0:
        y=1
    else:
        y=0
    return y

In [26]:
w, b=[0,-1], 0 # 초기조건
eta = 0.1

### 2-1.예측값, 실제값 비교

In [27]:
perc_f=[]
for a in range(4):
    perc_f.append(perc(X[a]))

In [28]:
perc_f==np.array(t) # 현재 예측값과 실제값이 같지 않음 

array([False,  True, False, False])

### 3. Training

In [29]:

for n in range(100):

    for i in range(4):
        error = t[i]- perc(X[i])

        
        w[0] = w[0] + eta * error * X[i][0]
        w[1] = w[1] + eta * error * X[i][1]
        b = b + eta * error

print("weight 1: {}, weight 2: {}, bias: {}".format(w[0],w[1],b))

weight 1: 0.30000000000000004, weight 2: 0.19999999999999987, bias: -0.09999999999999998


### 3-1 Training 후 예측값, 실제값 비교

In [30]:
perc_f=[]
for a in range(4):
    perc_f.append(perc(X[a]))

In [31]:
perc_f==np.array(t) # 예측값과 실제값이 같아짐 

array([ True,  True,  True,  True])

# Iris classifications

In [32]:
from sklearn import datasets
iris = datasets.load_iris() # 분꽃
iris.target_names # 3종류의 분꽃 분류하기
iris.feature_names # features

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

### 1. Data

In [33]:
X2=iris.data # input data # the number of input nodes = 4


In [34]:
iris.target_names # setosa = 0, not setosa = 1


array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [35]:
t2=np.where(iris.target>0,1,0) # 0(setosa) 과 1(setosa 외) 로 분류


### 2. Model

In [36]:
w2,b2=[0,0,0,0],1 # 초기조건 
eta2=0.1 

In [37]:
def perc2(x):
    f2=np.dot(w2,x)+b2
    if f2>=0:
        y2=1
    else:
        y2=0
    return y2

### 2-1. 예측값, 실제값 비교 

In [38]:
perc2_f=[]
for a in range(150):
    perc2_f.append(perc2(X2[a]))

In [39]:
perc2_f==t2 # 예측값, 실제값이 같지 않음 

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

### 3. Training

In [40]:

for n in range(1000):

    for j in range(150):
        error2 = t2[j]- perc2(X2[j])

        
        w2[0] = w2[0] + eta2 * error2 * X2[j][0]
        w2[1] = w2[1] + eta2 * error2 * X2[j][1]
        w2[2] = w2[2] + eta2 * error2 * X2[j][2]
        w2[3] = w2[3] + eta2 * error2 * X2[j][3]
        b2 = b2 + eta2 * error2


print("weight 1: {}, weight 2: {}, weight 3: {}, weight 4: {}, bias: {}".format(w2[0],w2[1],w2[2],w2[3],b2))

weight 1: -0.19999999999999973, weight 2: -0.7, weight 3: 1.0500000000000003, weight 4: 0.42999999999999994, bias: 0.8


### 3-1. Training 후 예측값, 실제값 비교

In [41]:
perc2_f=[]
for a in range(150):
    perc2_f.append(perc2(X2[a]))

In [42]:
perc2_f==t2 # 예측값, 실제값이 같아지므로, 모델이 잘 형성됨을 알 수 있음

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,